/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthRouteImport } from './pages/_auth'
import { Route as IndexRouteImport } from './pages/index'
import { Route as NotFoundIndexRouteImport } from './pages/not-found/index'
import { Route as LoginIndexRouteImport } from './pages/login/index'
import { Route as AuthUsersIndexRouteImport } from './pages/_auth/users/index'
import { Route as AuthHomeIndexRouteImport } from './pages/_auth/home/index'
import { Route as AuthUsersNewRouteImport } from './pages/_auth/users/new'
import { Route as AuthUsersIdRouteImport } from './pages/_auth/users/$id'
import { Route as AuthUsersIdIndexRouteImport } from './pages/_auth/users/$id/index'
import { Route as AuthUsersIdEditRouteImport } from './pages/_auth/users/$id/edit'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundIndexRoute = NotFoundIndexRouteImport.update({
  id: '/not-found/',
  path: '/not-found/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUsersIndexRoute = AuthUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHomeIndexRoute = AuthHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersNewRoute = AuthUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersIdRoute = AuthUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersIdIndexRoute = AuthUsersIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthUsersIdRoute,
} as any)
const AuthUsersIdEditRoute = AuthUsersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AuthUsersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login/': typeof LoginIndexRoute
  '/not-found/': typeof NotFoundIndexRoute
  '/users/$id': typeof AuthUsersIdRouteWithChildren
  '/users/new': typeof AuthUsersNewRoute
  '/home/': typeof AuthHomeIndexRoute
  '/users/': typeof AuthUsersIndexRoute
  '/users/$id/edit': typeof AuthUsersIdEditRoute
  '/users/$id/': typeof AuthUsersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/not-found': typeof NotFoundIndexRoute
  '/users/new': typeof AuthUsersNewRoute
  '/home': typeof AuthHomeIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/users/$id/edit': typeof AuthUsersIdEditRoute
  '/users/$id': typeof AuthUsersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/not-found/': typeof NotFoundIndexRoute
  '/_auth/users/$id': typeof AuthUsersIdRouteWithChildren
  '/_auth/users/new': typeof AuthUsersNewRoute
  '/_auth/home/': typeof AuthHomeIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
  '/_auth/users/$id/edit': typeof AuthUsersIdEditRoute
  '/_auth/users/$id/': typeof AuthUsersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/not-found/'
    | '/users/$id'
    | '/users/new'
    | '/home/'
    | '/users/'
    | '/users/$id/edit'
    | '/users/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/not-found'
    | '/users/new'
    | '/home'
    | '/users'
    | '/users/$id/edit'
    | '/users/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login/'
    | '/not-found/'
    | '/_auth/users/$id'
    | '/_auth/users/new'
    | '/_auth/home/'
    | '/_auth/users/'
    | '/_auth/users/$id/edit'
    | '/_auth/users/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  NotFoundIndexRoute: typeof NotFoundIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found/': {
      id: '/not-found/'
      path: '/not-found'
      fullPath: '/not-found/'
      preLoaderRoute: typeof NotFoundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthUsersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/home/': {
      id: '/_auth/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof AuthHomeIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/new': {
      id: '/_auth/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof AuthUsersNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/$id': {
      id: '/_auth/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AuthUsersIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/$id/': {
      id: '/_auth/users/$id/'
      path: '/'
      fullPath: '/users/$id/'
      preLoaderRoute: typeof AuthUsersIdIndexRouteImport
      parentRoute: typeof AuthUsersIdRoute
    }
    '/_auth/users/$id/edit': {
      id: '/_auth/users/$id/edit'
      path: '/edit'
      fullPath: '/users/$id/edit'
      preLoaderRoute: typeof AuthUsersIdEditRouteImport
      parentRoute: typeof AuthUsersIdRoute
    }
  }
}

interface AuthUsersIdRouteChildren {
  AuthUsersIdEditRoute: typeof AuthUsersIdEditRoute
  AuthUsersIdIndexRoute: typeof AuthUsersIdIndexRoute
}

const AuthUsersIdRouteChildren: AuthUsersIdRouteChildren = {
  AuthUsersIdEditRoute: AuthUsersIdEditRoute,
  AuthUsersIdIndexRoute: AuthUsersIdIndexRoute,
}

const AuthUsersIdRouteWithChildren = AuthUsersIdRoute._addFileChildren(
  AuthUsersIdRouteChildren,
)

interface AuthRouteChildren {
  AuthUsersIdRoute: typeof AuthUsersIdRouteWithChildren
  AuthUsersNewRoute: typeof AuthUsersNewRoute
  AuthHomeIndexRoute: typeof AuthHomeIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthUsersIdRoute: AuthUsersIdRouteWithChildren,
  AuthUsersNewRoute: AuthUsersNewRoute,
  AuthHomeIndexRoute: AuthHomeIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  NotFoundIndexRoute: NotFoundIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
